name: mspr
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # https://pub.dev/packages/firebase_core
  firebase_core: ^2.1.0
  # https://pub.dev/packages/firebase_analytics
  firebase_analytics: ^10.0.2
  # https://pub.dev/packages/firebase_remote_config
  firebase_remote_config: ^3.0.2
  # https://pub.dev/packages/firebase_crashlytics
  firebase_crashlytics: ^3.0.2
  package_info_plus: ^1.4.3+1
  # https://pub.dev/packages/flutter_easyloading
  flutter_easyloading: ^3.0.5
  # https://pub.dev/packages/hooks_riverpod
  hooks_riverpod: ^1.0.4
  # https://pub.dev/packages/flutter_keyboard_visibility
  flutter_keyboard_visibility: ^5.4.0
  # https://pub.dev/packages/auto_route
  auto_route: ^5.0.2
  # https://pub.dev/packages/firebase_auth
  firebase_auth: ^4.0.2
  # https://pub.dev/packages/get_it
  get_it: ^7.2.0
  # https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.2.13
  flutter_hooks: ^0.18.5+1
  # https://pub.dev/packages/dio
  dio: ^4.0.6
  # https://pub.dev/packages/retrofit
  retrofit: ^3.3.1
  # https://pub.dev/packages/dartz
  dartz: ^0.10.1
  # https://pub.dev/packages/loading_animation_widget
  loading_animation_widget: ^1.2.0+3
  # https://pub.dev/packages/dynamic_height_grid_view
  dynamic_height_grid_view: ^0.0.3
  # https://pub.dev/packages/flutter_barcode_scanner
  flutter_barcode_scanner: ^2.0.0
  # https://pub.dev/packages/qr_code_scanner
  qr_code_scanner: ^1.0.1
  # https://pub.dev/packages/ar_flutter_plugin
  ar_flutter_plugin: ^0.7.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/build_runner
  build_runner: ^2.3.0
  # https://pub.dev/packages/auto_route
  auto_route_generator: ^5.0.2
  # https://pub.dev/packages/retrofit_generator
  retrofit_generator: ^4.0.3+2
  # https://pub.dev/packages/change_app_package_name
  change_app_package_name: ^1.1.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/graphic/
    - assets/graphic/icons/
    - assets/config/

  # Enable generation of localized Strings from arb files.
  generate: true
